version: "3.8"

services:
  neo4j:
    image: neo4j:5-community
    container_name: cloudsync-support-neo4j
    ports:
      - "7474:7474" # Browser UI
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=neo4j/changeme-neo4j
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
